//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.FolderData
{
    using System;
    using System.Collections.Generic;
    
    public partial class SearchHelp
    {
        public int IdObject { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Name { get; set; }
        public Nullable<int> IdSection { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Section Section { get; set; }
    }
}
